# -*- coding: utf-8 -*-
"""good_bye.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uv7wgNKHqddnMoWR12YjOD5mljGRTtnY
"""

import random

def main():
  r = random.randint(0,25)
  for i in range(1,r):
    print("good bye sick building")

if __name__ == "__main__":
  main()