# -*- coding: utf-8 -*-
"""Hello_Buildings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AHOM2QrD2Ccu0bahmaFT4wrpGSPGKIa2
"""

def main():
  print("Hello Buildings!")

if __name__ == "__main__":
  main()